apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron-hourly-poll
  namespace: ingestion-system
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@hourly"
