[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.gofmt]
command = "gofmt"
options = ["-w"]
includes = ["*.go"]

[formatter.rustfmt]
command = "rustfmt"
options = ["--edition", "2021"]
includes = ["*.rs"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.json", "*.md", "*.yml", "*.yaml"]
