apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/namespace.yaml
  - path: patches/rename-subjects.yaml
  - path: patches/set-worker-image.yaml
